"""empty message

Revision ID: 3cd70771e165
Revises: f8a6400b2cb8
Create Date: 2026-07-24 12:42:48.203821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd70771e165'
down_revision = 'f8a6400b2cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('people_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('pokemon_name')

    # ### end Alembic commands ###
