"""empty message

Revision ID: 91a7d9e5982e
Revises: d38b63da1cf0
Create Date: 2026-08-13 16:47:39.503786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a7d9e5982e'
down_revision = 'd38b63da1cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_pokemon_favorite', schema=None) as batch_op:
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon_favorite', schema=None) as batch_op:
        batch_op.alter_column('pokemon_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
